environment:
  name: prod
  project: cdf-bootcamp-72-prod
  type: prod
  selected:
  - modules/

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-72-prod # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR prod/PROD DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: 47293f03-b1a5-452f-8c9e-a2d8d8b2d7d1
      # OBJECT ID FOR prod/PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: 302f5845-837e-4bed-bd58-1041294571ef
      # OBJECT ID FOR prod/PROD ADMIN TK ENTRA GROUP
      readonly_source_id: 302f5845-837e-4bed-bd58-1041294571ef
      # OBJECT ID FOR prod/PROD ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: 1ec16398-a432-40f9-8055-0f5ab17575d7
      # OBJECT ID FOR prod/PROD DATA DEVELOPER ENTRA GROUP
      data_developer_source_id: 40e7032a-2cf6-4209-81d7-f09e94e2d4bf
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi

      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee